CREATE TABLE IF NOT EXISTS Text
(
   ID INTEGER NOT NULL,
   TEXT VARCHAR (255) NOT NULL,
   PRIMARY KEY(id)
);

INSERT INTO Text(ID, TEXT) VALUES(1,'FIRST TEXT HELLO WORLD');
INSERT INTO Text(ID, TEXT) VALUES(2,'SECOND TEXT HELLO WORLD');
INSERT INTO Text(ID, TEXT) VALUES(3,'THIRD TEXT HELLO WORLD');
INSERT INTO Text(ID, TEXT) VALUES(4,'FOURTH TEXT HELLO WORLD');